language: ruby
rvm:
  - 2.3.0
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - RAILS_ENV=test bundle exec rake db:seed
  - bundle exec rspec
  - bundle exec cucumber

addons:
  code_climate:
     repo_token: a2dceb04e205507656996dc4a4fba5e2dff332d21e58217946359396b2684d65
